server.servlet.context-path=/symphony

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/symphony_sa}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
jwt.secretKey=${JWT_SECRETKEY:GrznEQ5++J4Uu2O8M03tDNmGLLuwiJ5mZ+7xKFmnNqfK/uxoaYFRDDZQGvlEsmP8}
jwt.validDuration=${JWT_VALID_DURATION:3600}
jwt.refreshableDuration=${JWT_REFRESHABLE_DURATION:2592000}

#server.port=8081
#logging.level.orrg.hibernate=ERROR
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB

upload-dir=${UPLOAD_DIR:D:/nienluan/Symphony-music-streaming-platforms/backend/uploads}

#server.tomcat.max-swallow-size=200MB

vnpay.TmnCode=${VNPAY_TMNCODE:your-vnpayTmnCode}
vnpay.secretKey=${VNPAY_SECRET_KEY:your-secretKey}

ai.service.url=${AI_SERVICE_URL:http://localhost:8000}